# Generated by Django 4.1.2 on 2023-03-07 11:27

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('add_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('content', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='add/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('publish',),
            },
        ),
        migrations.CreateModel(
            name='Future_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_event', models.IntegerField()),
                ('month_of_event', models.CharField(choices=[('Jan', '1'), ('Feb', '2'), ('Mar', '3'), ('Apr', '4'), ('May', '5'), ('June', '6'), ('July', '7'), ('Aug', '8'), ('Sept', '9'), ('Oct', '10'), ('Nov', '11'), ('Dec', '12')], max_length=10)),
                ('any_hashtag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('title1_like_what_we_do', models.CharField(blank=True, max_length=45)),
                ('content1', models.CharField(blank=True, max_length=200)),
                ('title2_like_how_we_do', models.CharField(blank=True, max_length=45)),
                ('content2', models.CharField(blank=True, max_length=200)),
                ('title_like_what_we_achieve', models.CharField(blank=True, max_length=45)),
                ('content3', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='initiatives/')),
                ('date_of_initiative', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('quote', models.CharField(blank=True, default="no use, don't write anything", max_length=40)),
                ('Social_media_handle', models.CharField(max_length=120)),
                ('handle_link', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('value_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('quote', models.TextField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='value/')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
