# Generated by Django 4.1.2 on 2023-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumini_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('quote', models.CharField(blank=True, default="no use, don't write anything", max_length=40)),
                ('Social_media_handle', models.CharField(max_length=120)),
                ('handle_link', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Developer_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('quote', models.CharField(blank=True, default="no use, don't write anything", max_length=40)),
                ('Social_media_handle', models.CharField(max_length=120)),
                ('handle_link', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('quote', models.CharField(blank=True, default="no use, don't write anything", max_length=40)),
                ('Social_media_handle', models.CharField(max_length=120)),
                ('handle_link', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Core_Team',
        ),
    ]
