# Generated by Django 4.1.2 on 2023-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_blogs', '0004_remove_developer_team_work_remove_media_team_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_content_management_Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
