# Generated by Django 4.1.2 on 2023-05-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_blogs', '0005_web_content_management_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media_Team',
            new_name='Third_year_core_Team',
        ),
    ]
