# Generated by Django 4.1.2 on 2023-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_blogs', '0006_rename_media_team_third_year_core_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='third_year_core_team',
            name='work',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
