# Generated by Django 4.1.2 on 2023-05-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_blogs', '0007_third_year_core_team_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Future_events',
            new_name='Past_events',
        ),
    ]
