# Generated by Django 4.1.2 on 2023-06-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_commentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimage',
            name='user',
        ),
        migrations.AddField(
            model_name='commentimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
