# Generated by Django 4.1.2 on 2023-06-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_commentimage_user_commentimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='likes',
        ),
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
