# Generated by Django 4.1.2 on 2023-06-10 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0005_remove_galleryimage_likes_delete_commentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
