# Generated by Django 4.1.2 on 2023-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryimage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
