# Generated by Django 4.1.2 on 2023-02-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_views_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
