# Generated by Django 4.1.2 on 2023-02-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
