# Generated by Django 4.1.2 on 2023-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
        ),
    ]
