# Generated by Django 4.1.2 on 2023-06-05 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0013_reply1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply1',
            new_name='Reply',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='body',
            new_name='body_reply',
        ),
    ]
