# Generated by Django 4.1.2 on 2023-06-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_rename_reply1_reply_rename_body_reply_body_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
