# Generated by Django 4.1.2 on 2023-06-12 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0016_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments_forum', to=settings.AUTH_USER_MODEL),
        ),
    ]
