# Generated by Django 4.1.2 on 2023-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_comment_comment_likes_count_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='comment_likes',
        ),
    ]
