# Generated by Django 4.1.2 on 2023-06-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_comment_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_dislikes_count',
        ),
    ]
