# Generated by Django 4.1.2 on 2022-12-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_with_image',
            name='excerpt',
            field=models.TextField(max_length=1000),
        ),
    ]
