# Generated by Django 4.1.2 on 2023-04-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_with_image_tags_for_seo_and_search_bar_in_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_with_image',
            name='tags_for_seo_and_search_bar_in_website',
            field=models.TextField(help_text='Add tags for search'),
        ),
    ]
