# Generated by Django 4.1.2 on 2023-04-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_with_image_tags_for_seo_and_search_bar_in_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_with_image',
            name='tags_for_seo_and_search_bar_in_website',
            field=models.TextField(help_text='Add tags(this tags will be for search bar of the webstie as well as for SEO stuffs, so be particular while adding, do research for the keywords, and add properly.'),
        ),
    ]
