# Generated by Django 4.1.2 on 2023-04-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_with_image_tags_for_seo_and_search_bar_in_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
