# Generated by Django 4.1.2 on 2023-05-07 06:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indic_r', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='proshow',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='socialinitiative',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='about_talk_in_nutshell',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
