# Generated by Django 4.1.2 on 2023-03-01 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='user_avtar.webp', null=True, upload_to='users/')),
                ('website', models.CharField(max_length=244)),
                ('github', models.CharField(max_length=244)),
                ('twitter', models.CharField(max_length=244)),
                ('instagram', models.CharField(max_length=244)),
                ('facebook', models.CharField(max_length=244)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
