# Generated by Django 4.1.2 on 2023-04-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/images/user_avtar.webp', null=True, upload_to='users/'),
        ),
    ]
